

name: Build and test Cookbook app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'
    - name: Install dependancies
      run: npm install
    - name: Run UNIT tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo "dsiren"

  run-ui-test:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'
    - name: Install dependancies
      run: npm install
    - name: Playwright install
      run: npx playwright install
    - name: Start the app
      run: npm run start &
    - name: Run UI test
      run: npm run test:ui

  deploy:
    runs-on: ubuntu-latest
    needs: run-ui-test
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}